# Adds a "Sponsor" button to the repository.
# Uncomment and fill in the platforms you actually use; delete the rest.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [imirfanul]
# open_collective: structyl
# patreon: # your Patreon username
# ko_fi: # your Ko-fi username
# buy_me_a_coffee: # your username
# custom: ['https://www.imirfanul.com']
