// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from "eslint-plugin-storybook";

import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';

export default [js.configs.recommended, {
  files: ['**/*.{ts,tsx}'],
  languageOptions: {
    parser: tsparser,
    parserOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      ecmaFeatures: { jsx: true },
    },
    globals: {
      window: 'readonly',
      document: 'readonly',
      navigator: 'readonly',
      console: 'readonly',
      process: 'readonly',
      globalThis: 'readonly',
      setTimeout: 'readonly',
      clearTimeout: 'readonly',
      setInterval: 'readonly',
      clearInterval: 'readonly',
      requestAnimationFrame: 'readonly',
      cancelAnimationFrame: 'readonly',
      queueMicrotask: 'readonly',
      Blob: 'readonly',
      URL: 'readonly',
      File: 'readonly',
      FileList: 'readonly',
      FormData: 'readonly',
      DOMRect: 'readonly',
      CustomEvent: 'readonly',
      Element: 'readonly',
      HTMLElement: 'readonly',
      HTMLInputElement: 'readonly',
      HTMLButtonElement: 'readonly',
      HTMLDivElement: 'readonly',
      HTMLSpanElement: 'readonly',
      HTMLAnchorElement: 'readonly',
      HTMLImageElement: 'readonly',
      HTMLTextAreaElement: 'readonly',
      HTMLOListElement: 'readonly',
      HTMLUListElement: 'readonly',
      HTMLLIElement: 'readonly',
      HTMLHeadingElement: 'readonly',
      HTMLParagraphElement: 'readonly',
      HTMLFormElement: 'readonly',
      HTMLLabelElement: 'readonly',
      HTMLTableElement: 'readonly',
      HTMLSelectElement: 'readonly',
      SVGSVGElement: 'readonly',
      MutationObserver: 'readonly',
      ResizeObserver: 'readonly',
      IntersectionObserver: 'readonly',
      NodeFilter: 'readonly',
      Node: 'readonly',
      DocumentFragment: 'readonly',
      PointerEvent: 'readonly',
      KeyboardEvent: 'readonly',
      MouseEvent: 'readonly',
      FocusEvent: 'readonly',
      Event: 'readonly',
      AnimationEvent: 'readonly',
      TransitionEvent: 'readonly',
      Image: 'readonly',
      Window: 'readonly',
      Document: 'readonly',
      TouchEvent: 'readonly',
      WindowEventMap: 'readonly',
      DocumentEventMap: 'readonly',
      HTMLElementEventMap: 'readonly',
      EventListener: 'readonly',
      StorageEvent: 'readonly',
      MediaQueryListEvent: 'readonly',
      AbortController: 'readonly',
      AbortSignal: 'readonly',
      fetch: 'readonly',
      CSSStyleDeclaration: 'readonly',
      MutationRecord: 'readonly',
      getComputedStyle: 'readonly',
      ValidityState: 'readonly',
      alert: 'readonly',
      React: 'readonly',
      // SVG element types
      SVGElement: 'readonly',
      SVGGElement: 'readonly',
      SVGRectElement: 'readonly',
      SVGPathElement: 'readonly',
      SVGPolygonElement: 'readonly',
      SVGCircleElement: 'readonly',
      // HTML table / misc element types
      HTMLTableCaptionElement: 'readonly',
      HTMLTableSectionElement: 'readonly',
      HTMLTableRowElement: 'readonly',
      HTMLTableCellElement: 'readonly',
      HTMLTimeElement: 'readonly',
      HTMLVideoElement: 'readonly',
      HTMLCanvasElement: 'readonly',
      HTMLMediaElement: 'readonly',
      MediaError: 'readonly',
      localStorage: 'readonly',
      sessionStorage: 'readonly',
      // Vitest globals (test files)
      describe: 'readonly',
      test: 'readonly',
      it: 'readonly',
      expect: 'readonly',
      vi: 'readonly',
      beforeEach: 'readonly',
      afterEach: 'readonly',
      beforeAll: 'readonly',
      afterAll: 'readonly',
    },
  },
  plugins: {
    '@typescript-eslint': tseslint,
    react,
    'react-hooks': reactHooks,
  },
  rules: {
    ...tseslint.configs.recommended.rules,
    ...react.configs.recommended.rules,
    ...reactHooks.configs.recommended.rules,
    'react/react-in-jsx-scope': 'off',
    'react/prop-types': 'off',
    '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
    'no-redeclare': 'off',
    'no-unused-vars': 'off',
    '@typescript-eslint/no-empty-object-type': 'off',
    'react/no-unknown-property': ['error', { ignore: ['cmdk-group-heading', 'cmdk-input-wrapper'] }],
  },
  settings: { react: { version: 'detect' } },
}, prettier, { ignores: ['**/dist/**', '**/.next/**', '**/node_modules/**', '**/coverage/**'] }, ...storybook.configs["flat/recommended"]];
