/**
 * @structyl/primitives — Chart
 *
 * Headless SVG chart primitives. No external chart library dependencies.
 * Provides all layout algorithms, scale functions, and path generators.
 */

// Main components
export {
  Root,
  Grid,
  XAxis,
  YAxis,
  Bar,
  Line,
  Area,
  Scatter,
  Bubble,
  Tooltip,
  Legend,
  PieRoot,
  Pie,
  PieCenterLabel,
  RadarRoot,
  PolarGrid,
  PolarAngleAxis,
  Radar,
  Heatmap,
  Treemap,
  Funnel,
  Gauge,
  GaugeContainer,
  GaugeValueArc,
  GaugeReferenceArc,
  GaugePointer,
  Candlestick,
  SparkLine,
  RangeBar,
  RangeArea,
  ReferenceLine,
  ReferenceArea,
  RadialBarRoot,
  RadialBar,
  RadialLineRoot,
  RadialLine,
  Waterfall,
  Sankey,
  Pyramid,
  Gantt,
  Histogram,
  Boxplot,
  Sunburst,
  Chord,
  LinearGauge,
} from './chart';

// Type exports
export type {
  ChartRootProps,
  ChartPieRootProps,
  ChartRadarRootProps,
  ChartMargin,
  ChartDimensions,
  ChartXAxisProps,
  ChartYAxisProps,
  ChartGridProps,
  ChartBarProps,
  ChartLineProps,
  ChartAreaProps,
  ChartScatterProps,
  ChartBubbleProps,
  ChartPieProps,
  ChartPolarGridProps,
  ChartPolarAngleAxisProps,
  ChartRadarProps,
  ChartHeatmapProps,
  ChartTreemapProps,
  ChartFunnelProps,
  ChartGaugeProps,
  ChartGaugeContainerProps,
  ChartGaugeValueArcProps,
  ChartGaugeReferenceArcProps,
  ChartGaugePointerProps,
  GaugeContextValue,
  ChartCandlestickProps,
  ChartTooltipProps,
  ChartLegendProps,
  CartesianContextValue,
  PieContextValue,
  RadarContextValue,
  TooltipState,
  TooltipPayloadEntry,
  TreemapNode,
  OhlcEntry,
  FunnelEntry,
  CurveType,
  AxisScale,
  LegendPosition,
  LabelPosition,
  HighlightScope,
  MarkShape,
  ScatterMarkerShape,
  ChartSparkLineProps,
  ChartRangeBarProps,
  ChartRangeAreaProps,
  ChartReferenceLineProps,
  ChartReferenceAreaProps,
  ChartRadialBarRootProps,
  ChartRadialBarProps,
  ChartRadialLineRootProps,
  ChartRadialLineProps,
  ChartWaterfallProps,
  ChartSankeyProps,
  ChartPyramidProps,
  ChartGanttProps,
  ChartHistogramProps,
  ChartBoxplotProps,
  BoxplotEntry,
  ChartSunburstProps,
  SunburstNode,
  ChartChordProps,
  ChartLinearGaugeProps,
  ChartPieCenterLabelProps,
  WaterfallEntry,
  SankeyNode,
  SankeyLink,
  GanttTask,
} from './chart.types';

// Scale utilities (useful for custom extensions)
export {
  linearScale,
  logScale,
  bandScale,
  ordinalScale,
  niceLinearTicks,
  niceDomain,
  extent,
  computeYDomain,
} from './scales';

// Path generators (useful for custom chart types)
export {
  buildLinePath,
  buildAreaPath,
  buildAreaPathFlat,
  buildArcPath,
  buildRadarPath,
  buildBarRect,
  fmt,
} from './paths';

// Layout algorithms
export {
  squarifyTreemap,
  computeFunnelLayout,
  computeGaugeArcs,
  computeCandlestickBars,
  computeHeatmapCells,
} from './layout';

export type {
  TreemapLayoutNode,
  FunnelLayoutSegment,
  GaugeArcData,
  CandlestickBar,
  HeatmapCell,
} from './layout';

export type { BarRectProps } from './paths';
